# Site settings
permalink: /posts/:year/:month/:day/:title/
title: Facebook React Native 教程
tagline: Connecting Facebook's Open Source projects
fbappid: ""
gacode: "UA-43024238-14"
description: >
  Facebook 2016 年 F8 app 的中文教程。React Native 的官方最佳实践，应该是最好的 React Native 学习资料了。从服务器端到 App，包括 Redux，Relay，GraphQL。教程涵盖：如何进行 app 技术选型，如何做跨平台设计，如何做 React Native 的测试。
baseurl:
url: https://f8-app-tutorial-cn.liaohuqiu.net
ghrepo: "liaohuqiu/f8-app-tutorial-cn"

exclude:        ['base.sh', 'manager.sh', '_docker']

# Build settings
gems:
  - jekyll-feed
markdown: kramdown
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  docs:
    output: true
    permalink: /tutorials/:name/
  support:
    output: true
    permalink: /support/

sass:
  style: :compressed

color:
  # Provides colour for background of top header of homepage
  primary: "#dc6f62"
  # Provides colour for background of elsewhere on site
  secondary: "#f8f8f8"
  # A color that will work for buttons laid on top of primary colour
  light: "#4ea2ce"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#393939"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#dc6f62"
  # Text of links in the nav
  navtext: "#fff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#dc6f62"
